# Generated by nixos-generate-config — safe to commit, no secrets.
# LUKS UUID identifies the encrypted device but does not weaken encryption.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    # LUKS-encrypted BTRFS root
    boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/f6f8d7e0-c24d-48c0-9414-69e47448f12e";

    fileSystems."/" =     { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@" ]; };
    fileSystems."/home" = { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@home" ]; };
    fileSystems."/nix" =  { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@nix" ]; };
    fileSystems."/var/log" = { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@log" ]; };

    fileSystems."/boot" = { device = "/dev/disk/by-uuid/53B1-65CA"; fsType = "vfat"; options = [ "fmask=0022" "dmask=0022" ]; };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
